### ISSUE TITLE
Contributing User Stream

### ISSUE THREAD

**Issue by Ahaberling** [GtheSheep/tap-tableau#2]
Hello GtheSheep,

I added a stream retrieving Tableau user data to your tap. May I contribute with a PR? And if so, are there any contribution guidelines I should follow?

Cheers,
Alex

**Comment by GtheSheep** [comment]
does the USERS_METADATA stream cover your use case?

**Comment by Ahaberling** [comment]
Hey GtheSheep, 

no, I think. At least not in the way it is implemented currently. I need data about the users last login date, their role and their name and/or email. If you find a way to integrate this data into the USERS_METADATA stream, let me know. Then I will adjust my tap configuration.

Cheers,
Alex

**Comment by GtheSheep** [comment]
Hey!

Ahh I'm with you now, yeah these are currently all stored in the USERS field of the GROUPS stream, I should probably add an independent users stream for ease of use, but have added last_login_at the GROUPS.USERS for now in case that helps you?

Cheers,
Gary
